version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: coding_resources_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coding_resources
      MYSQL_USER: coding_user
      MYSQL_PASSWORD: coding_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
